/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioRecorder: typeof import('./../src/components/AudioRecorder/AudioRecorder.vue')['default']
    'AudioRecorder copy': typeof import('./../src/components/AudioRecorder/AudioRecorder copy.vue')['default']
    copy: typeof import('./../src/components/AudioRecorder/AudioRecorder copy.vue')['default']
    DictTag: typeof import('./../src/components/DictTag/index.vue')['default']
    DragUploadFile: typeof import('./../src/components/DragUploadFile/DragUploadFile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconFont: typeof import('./../src/components/icon-font/icon-font.vue')['default']
    KcTable: typeof import('./../src/components/KcTable/KcTable.vue')['default']
    MarqueeNotice: typeof import('./../src/components/MarqueeNotice/MarqueeNotice.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/Pagination.vue')['default']
    PasswordStrength: typeof import('./../src/components/PasswordStrength/PasswordStrength.vue')['default']
    ProgressSlider: typeof import('./../src/components/ProgressSlider/ProgressSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableGender: typeof import('./../src/components/TableGender/TableGender.vue')['default']
    UploadFile: typeof import('./../src/components/UploadFile/UploadFile.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
