/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioRecorder: typeof import('./../src/components/AudioRecorder/AudioRecorder.vue')['default']
    'AudioRecorder copy': typeof import('./../src/components/AudioRecorder/AudioRecorder copy.vue')['default']
    copy: typeof import('./../src/components/AudioRecorder/AudioRecorder copy.vue')['default']
    DictTag: typeof import('./../src/components/DictTag/index.vue')['default']
    DragUploadFile: typeof import('./../src/components/DragUploadFile/DragUploadFile.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IconFont: typeof import('./../src/components/icon-font/icon-font.vue')['default']
    KcTable: typeof import('./../src/components/KcTable/KcTable.vue')['default']
    MarqueeNotice: typeof import('./../src/components/MarqueeNotice/MarqueeNotice.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/Pagination.vue')['default']
    PasswordStrength: typeof import('./../src/components/PasswordStrength/PasswordStrength.vue')['default']
    ProgressSlider: typeof import('./../src/components/ProgressSlider/ProgressSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableGender: typeof import('./../src/components/TableGender/TableGender.vue')['default']
    UploadFile: typeof import('./../src/components/UploadFile/UploadFile.vue')['default']
  }
}
